Blackbox field disable preset
betaflight/firmware-presets pull request #110
Opened 2021-12-10 02:41 UTC by sugaarK

this preset alloys to disable logging of the individual data streams in blackbox. useful for saving space or CPU resources on less powerful chipsets.

2021-12-10 03:15 UTC, limonspb commented on presets/4.3/other/blackbox_disable.txt
> +#$ OPTION BEGIN (UNCHECKED): disable MAGNOMETER data
Magnometer :)

2021-12-10 05:54 UTC, limonspb requested changes
Magnometer - Magnetometer :)
And lets start all option names from the Capital letter please

2021-12-10 08:11 UTC, sugaarK commented on presets/4.3/other/blackbox_disable.txt
> +#$ OPTION BEGIN (UNCHECKED): disable MAGNOMETER data
done

2021-12-10 08:20 UTC, sugaarK commented
> Magnometer - Magnetometer :)
> And lets start all option names from the Capital letter please

fixed

2021-12-11 07:54 UTC, limonspb approved these changes

2021-12-11 07:55 UTC, merged