Create karate_race_lite.txt
betaflight/firmware-presets pull request #272
Opened 2022-07-01 08:46 UTC by sugaarK

This racing tune was developed from the Karate Race tune ti suit my new Viper lite ultralite 5" racer project. [Viper Lite](https://rotorbuilds.com/build/29775)
<img width="1426" alt="Screen Shot 2022-07-01 at 6 03 47 pm" src="https://user-images.githubusercontent.com/83344205/176859644-0e4df7f5-e86f-41de-8b92-fc95275ab13c.png">

2022-07-01 16:23 UTC, KarateBrot requested changes

2022-07-01 16:23 UTC, KarateBrot commented on presets/4.3/tune/karate_race_lite.txt
> +#$ DESCRIPTION: <img src="https://user-images.githubusercontent.com/83344205/176923532-e7791ff9-aa4f-457e-8222-78bd589c0b5d.png" width="400px" style="margin-left: auto; margin-right: auto; display: b
```suggestion
#$ DESCRIPTION: <img src="https://user-images.githubusercontent.com/19867640/176932353-fdc42c5e-33ae-42d7-b34c-e981b6cffa3f.png" style="max-width: 100%; margin-left: auto; margin-right: auto; display: block;"/>
```

2022-07-01 20:15 UTC, SupaflyFPV commented
Sick Image

2022-07-01 22:02 UTC, limonspb commented
plz don't make me comment "plz squash" and always keep 1 commit :)

2022-07-02 08:00 UTC, sugaarK commented
> plz don't make me comment "plz squash" and always keep 1 commit in the PR ready to merge :)

I would have but I was at work and can't nerd to the required level on my fone

2022-07-02 08:00 UTC, sugaarK commented on presets/4.3/tune/karate_race_lite.txt
> +#$ DESCRIPTION: <img src="https://user-images.githubusercontent.com/83344205/176923532-e7791ff9-aa4f-457e-8222-78bd589c0b5d.png" width="400px" style="margin-left: auto; margin-right: auto; display: b
done

2022-07-02 10:21 UTC, KarateBrot approved these changes

2022-07-02 10:50 UTC, limonspb commented on presets/4.3/tune/karate_race_lite.txt
> +#$ DESCRIPTION: This racing tune was developed from the Karate Race tune ti suit my new Viper lite ultralite 5" racer project. [Viper Lite](https://rotorbuilds.com/build/29775)
**to** suit :)

2022-07-02 12:49 UTC, KarateBrot approved these changes

2022-07-02 13:34 UTC, merged