Adds MSP option to OpenVTx
betaflight/firmware-presets pull request #287
Opened 2022-09-26 20:54 UTC by JyeSmith

This PR adds the MSP option to the OpenVTx preset.

Since the normal MSP setup requires 4 user steps (select port, baud, msp-vtx, and enter the CLI to set MSP to half duplex) I have tried to simplify this for the users by added the port selection to the preset.  A single check and everything is auto setup 😃 

There are also minor changes to the KEYWORDS and to uncheck TRAMP as the default.  MSP should be encouraged due to the auto configuration of the VTx tables.  Should the DISCUSSION be updated to also include this PR?

To test, OpenVTx master can be flashed with PIO or a binary downloaded from [here ](https://github.com/OpenVTx/OpenVTx/pull/40#issuecomment-1170598763) and the Configurator used to upload https://openvtx.org/

2022-09-26 21:06 UTC, JyeSmith commented
> MSP over VTX is only available on 4.4 ?

Yep, so what will be the best way to hand that?  SA and TRAMP are supported in earlier versions, and I dont want to end up with 2 presets for different versions.

2022-09-26 21:47 UTC, haslinghuis commented
Afaik you have to make a preset for 4.2 / 4.3 with SA / TRAMP and a 4.4 preset with MSP (as SA & TRAMP won't be needed anymore in 4.4). @limonspb are there any provisions to make this happen in one preset?

2022-09-26 23:38 UTC, limonspb commented
> Afaik you have to make a preset for 4.2 / 4.3 with SA / TRAMP and a 4.4 preset with MSP (as SA & TRAMP won't be needed anymore in 4.4). @limonspb are there any provisions to make this happen in one preset?

@JyeSmith you can name your new MSP group like that:
#$ OPTION_GROUP BEGIN: MSP (Betaflight 4.4+)
Just to notify users that these options won't work in 4.2 and 4.3
Or two separate presets are also fine.

@haslinghuis but that's a good idea for me to think about in the future.

2022-09-26 23:42 UTC, limonspb requested changes
@JyeSmith besides adding (Betaflight 4.4+) in the group name i would also suggest to add
`#$ FORCE_OPTIONS_REVIEW`, usually goes somewhere before or after #$DISCUSSION

It makes sure that the user clicks on the options before he picks a preset.
This preset now just won't do anything if user don't check the options, so there we go.

2022-09-27 06:44 UTC, limonspb commented
looks good, please squash and ready to go

2022-09-27 06:48 UTC, limonspb approved these changes

2022-09-27 06:57 UTC, limonspb approved these changes

2022-09-27 07:22 UTC, JyeSmith commented
Sorry for the spam... I think Im done 😄

2022-09-27 08:13 UTC, merged

2022-09-27 09:00 UTC, sugaarK commented
Amazing @JyeSmith

2022-10-12 06:44 UTC, sugaarK commented
didn't think about this at the time but it should be a new preset in the new 4.4 folder and leave the 4.3 version as it was

2022-10-12 07:01 UTC, limonspb commented
> didn't think about this at the time but it should be a new preset in the new 4.4 folder and leave the 4.3 version as it was

Could be ok here, he mentioned the BF version in the options. Options still needed here cuz even in 4.4 not everyone needs MSP maybe?

2022-10-12 07:26 UTC, JyeSmith commented
Would that then mean there are 2 files to maintain?  It would be great if it could stay and there was only 1.