Adding FIRMWARE_VERSION 4.4 to some OTHER tunes
betaflight/firmware-presets pull request #320
Opened 2022-11-04 04:55 UTC by limonspb

Remaining to check that im not sure:
reset_launch_mode.txt
reset_names.txt
reset_servo.txt
@TehllamaFPV  OTHER presets

2022-11-04 21:17 UTC, ctzsnooze submitted a review, later dismissed

2022-11-04 21:33 UTC, haslinghuis approved these changes

2022-11-04 23:41 UTC, ctzsnooze commented
PS @limonspb one thing to note is that in 4.4 there are only 4 rate profiles and 4 PID profiles.  Some Presets had settings for PID profiles 5 and 6, which will cause errors in 4.4.

2022-11-04 23:54 UTC, haslinghuis requested changes

2022-11-04 23:54 UTC, haslinghuis commented on presets/4.3/other/Street_League_motor_outputs.txt
> +            set throttle_limit_percent = 75
Please remove

2022-11-05 00:39 UTC, TehllamaFPV commented
It was the rateprofiles.
I'm also encountering silly problems where the addition of the fourth profile is missing in some 'back to default' behaviors.  I need to go back through there - so far it's been a nonissue because it's all been fresh flashes for me, but that's the kind of unit testing that I'm bad about doing

2022-11-05 10:08 UTC, limonspb commented
> PS @limonspb one thing to note is that in 4.4 there are only 4 rate profiles and 4 PID profiles. Some Presets had settings for PID profiles 5 and 6, which will cause errors in 4.4.

good catch!

2022-11-05 21:55 UTC, haslinghuis approved these changes

2022-11-05 21:55 UTC, merged