updated karate tunes
betaflight/firmware-presets pull request #368
Opened 2023-03-02 13:01 UTC by sugaarK

updated karate 6s tune to slider

and added suagrK rates as a file to all karate tunes
along with the RClink files

2023-03-03 09:55 UTC, limonspb requested changes
And lets make karate race as experimental temporarly cuz it has lots of text changes.

2023-03-03 09:55 UTC, limonspb commented on presets/4.4/tune/karate/karate_brushless_whoop.txt
>          set roll_expo = 54
this could be wrong

2023-03-04 00:03 UTC, KarateBrot submitted a review, later dismissed

2023-03-04 00:03 UTC, KarateBrot commented on presets/4.4/tune/karate/karate_brushless_whoop.txt
> +         #$ INCLUDE: presets/4.3/rc_link/generic/1000hz_race.txt
```suggestion
        #$ INCLUDE: presets/4.3/rc_link/generic/1000hz_race.txt
```

2023-03-04 00:03 UTC, KarateBrot commented on presets/4.4/tune/karate/karate_brushless_whoop.txt
> +         #$ INCLUDE:presets/4.3/rc_link/generic/250hz_race.txt
```suggestion
        #$ INCLUDE:presets/4.3/rc_link/generic/250hz_race.txt
```

2023-03-04 00:03 UTC, KarateBrot commented on presets/4.4/tune/karate/karate_brushless_whoop.txt
> +         #$ INCLUDE: presets/4.3/rc_link/generic/500hz_race.txt
```suggestion
        #$ INCLUDE: presets/4.3/rc_link/generic/500hz_race.txt
```

2023-03-06 07:05 UTC, KarateBrot requested changes
You reverted the changes by accident

2023-03-06 07:05 UTC, KarateBrot commented on presets/4.4/tune/karate/karate_brushless_whoop.txt
> +         #$ INCLUDE: presets/4.3/rc_link/generic/1000hz_race.txt
```suggestion
        #$ INCLUDE: presets/4.3/rc_link/generic/1000hz_race.txt
```

2023-03-06 07:05 UTC, KarateBrot commented on presets/4.4/tune/karate/karate_brushless_whoop.txt
> +         #$ INCLUDE:presets/4.3/rc_link/generic/250hz_race.txt
```suggestion
        #$ INCLUDE:presets/4.3/rc_link/generic/250hz_race.txt
```

2023-03-06 07:05 UTC, KarateBrot commented on presets/4.4/tune/karate/karate_brushless_whoop.txt
> +         #$ INCLUDE: presets/4.3/rc_link/generic/500hz_race.txt
```suggestion
        #$ INCLUDE: presets/4.3/rc_link/generic/500hz_race.txt
```

2023-03-06 07:16 UTC, KarateBrot approved these changes

2023-03-06 07:17 UTC, merged