ozr-5x tune preset BF 4.5
betaflight/firmware-presets pull request #471
Opened 2024-06-18 23:28 UTC by limonspb

5" frame racing tune by Dindrones and Benjamin Freelove

2024-06-19 00:11 UTC, sugaarK reviewed
3 blade props hit the fundamental  and the  second harmonic  pretty hard. Turning off the last one doesn’t save any thing in terms of latency vs the second. Use the rpm weight to reduce the first harmonic. This is a much better approach to tuning 4.5.

2024-06-19 00:13 UTC, sugaarK commented on presets/4.5/tune/ozr_5x.txt
> +set iterm_relax_cutoff = 20
I’d make this 45 as well, tracks better

2024-06-19 07:17 UTC, limonspb commented
Waiting for Benjamin to reply :)

2024-06-20 17:44 UTC, KarateBrot requested changes

2024-06-20 17:44 UTC, KarateBrot commented on presets/4.5/tune/ozr_5x.txt
> +#$ DESCRIPTION: - **YOU HAVE TO USE RPM FILTERING WITH THIS TUNE!** Failure to do so might result in fire ðŸ”¥
```suggestion
#$ DESCRIPTION: - **YOU HAVE TO USE RPM FILTERING WITH THIS TUNE!** Failure to do so might result in fire 🔥
```

2024-06-20 17:44 UTC, KarateBrot commented on presets/4.5/tune/ozr_5x.txt
> +#$ DESCRIPTION: This 6S racing tune is based on Karate Race 6s 5" (non spicy) by KarateBrot with very minor changes.
```suggestion
#$ DESCRIPTION: This 6S racing tune is based on Karate Race 6s 5" (non spicy) by sugarK with very minor changes.
```

2024-06-20 17:49 UTC, haslinghuis commented on presets/4.5/tune/ozr_5x.txt
> +#$ DESCRIPTION: - **YOU HAVE TO USE RPM FILTERING WITH THIS TUNE!** Failure to do so might result in fire ðŸ”¥
`ðŸ¤£`

2024-06-20 23:26 UTC, limonspb commented on presets/4.5/tune/ozr_5x.txt
> +#$ DESCRIPTION: - **YOU HAVE TO USE RPM FILTERING WITH THIS TUNE!** Failure to do so might result in fire ðŸ”¥
> `ðŸ¤£`

Ÿð¤ðŸ¤£

2024-06-20 23:39 UTC, haslinghuis commented on presets/4.5/tune/ozr_5x.txt
> +#$ DESCRIPTION: - **YOU HAVE TO USE RPM FILTERING WITH THIS TUNE!** Failure to do so might result in fire ðŸ”¥
âœŒ

2024-06-21 05:48 UTC, limonspb commented
@sugaarK 
updated based on your suggestions
And removed some values that are = to 4.5 defaults

2024-06-21 05:54 UTC, sugaarK approved these changes

2024-06-21 06:41 UTC, merged