Presets for new AOS Cine Frames
betaflight/firmware-presets pull request #494
Opened 2024-11-01 09:51 UTC by ChrisRosser

Hi Everyone,

I'm launching some new Cine frames over the next few days and wanted to create presets so that people find them easy to tune. The tunes should be in the same style as previous submissions.

Thank you in advance for taking a look over them and I stand ready to make any alterations needed to esnure they meet our high Betaflight standards!

2024-11-01 15:09 UTC, limonspb commented on presets/4.5/filters/aos_rc/aos_cine40_filters.txt
> +#$ DESCRIPTION: NOTE this needs bidirectional Dshot support and RPM filtering active to use. DO NOT ATEMPT TO USE WITH OUT RPM FILTERING!
should be "WITHOUT" and in a few places

2024-11-01 15:10 UTC, limonspb commented on presets/4.5/tune/aos_rc/aos_cine20_tune.txt
> +    #$ INCLUDE: presets/4.5/filters/aos_rc/aos_cine20_filters.txt
need a tab for padding for whats inside OPTIONS

2024-11-01 16:08 UTC, haslinghuis requested changes

2024-11-01 16:08 UTC, haslinghuis commented on presets/4.5/filters/aos_rc/aos_cine20_filters.txt
> +#$ DESCRIPTION: NOTE this needs bidirectional Dshot support and RPM filtering active to use. DO NOT ATEMPT TO USE WITH OUT RPM FILTERING!
```suggestion
#$ DESCRIPTION: NOTE this needs bidirectional Dshot support and RPM filtering active to use. DO NOT ATTEMPT TO USE WITHOUT RPM FILTERING!
```

2024-11-01 16:08 UTC, haslinghuis commented on presets/4.5/filters/aos_rc/aos_cine30_filters.txt
> +#$ DESCRIPTION: NOTE this needs bidirectional Dshot support and RPM filtering active to use. DO NOT ATEMPT TO USE WITH OUT RPM FILTERING!
```suggestion
#$ DESCRIPTION: NOTE this needs bidirectional Dshot support and RPM filtering active to use. DO NOT ATTEMPT TO USE WITHOUT RPM FILTERING!
```

2024-11-01 16:08 UTC, haslinghuis commented on presets/4.5/filters/aos_rc/aos_cine35_filters.txt
>  #$ DESCRIPTION: NOTE this needs bidirectional Dshot support and RPM filtering active to use. DO NOT ATEMPT TO USE WITH OUT RPM FILTERING!
```suggestion
#$ DESCRIPTION: NOTE this needs bidirectional Dshot support and RPM filtering active to use. DO NOT ATTEMPT TO USE WITHOUT RPM FILTERING!
```

2024-11-01 16:08 UTC, haslinghuis commented on presets/4.5/filters/aos_rc/aos_cine40_filters.txt
> +#$ DESCRIPTION: NOTE this needs bidirectional Dshot support and RPM filtering active to use. DO NOT ATEMPT TO USE WITH OUT RPM FILTERING!
```suggestion
#$ DESCRIPTION: NOTE this needs bidirectional Dshot support and RPM filtering active to use. DO NOT ATTEMPT TO USE WITHOUT RPM FILTERING!
```

2024-11-01 17:04 UTC, limonspb commented
@ChrisRosser Can't comment on the tune parameters much, but looks good overall.
Please fix the minor typos, and padding for options here and there.
New presets must be EXPERIMENTAL at first. But we are less strict about it now :)

Small problem:
if filter preset uses a slider or sliders, it's better to do `simplified_tuning apply`.

On a side note:
If you want, then filter options can be checked by default inside a tune preset.
Also sag compensation can be checked by default, since it goes under TUNE umbrella too.
And if you are using simplified tuning sliders, you don't have to list all pid values. Unless you want to.

2024-11-04 11:27 UTC, ChrisRosser commented
@limonspb and @haslinghuis 

Thank you for your review and suggestions. I have made all the suggested whitespace changes. All of these tunes are based on the Cine25 and Cine35 tunes which have been used in the community for over a year without any issues so I'm confident they will be safe for anyone in the community to use. I've also set the MM to 1.0 on the new tunes which should be very very safe (I'm running around 1.5 MM on all my drones)👍

2024-11-04 17:43 UTC, limonspb commented
> @limonspb and @haslinghuis
> 
> Thank you for your review and suggestions. I have made all the suggested whitespace changes. All of these tunes are based on the Cine25 and Cine35 tunes which have been used in the community for over a year without any issues so I'm confident they will be safe for anyone in the community to use. I've also set the MM to 1.0 on the new tunes which should be very very safe (I'm running 1.5 MM on all my drones)👍

Any reason you didn't use `simplified_tuning apply` in the filter settings?
This command sets the proper values for the active sliders only.

2024-11-06 08:35 UTC, ChrisRosser commented
> > @limonspb and @haslinghuis
> > Thank you for your review and suggestions. I have made all the suggested whitespace changes. All of these tunes are based on the Cine25 and Cine35 tunes which have been used in the community for over a year without any issues so I'm confident they will be safe for anyone in the community to use. I've also set the MM to 1.0 on the new tunes which should be very very safe (I'm running 1.5 MM on all my drones)👍
> 
> Any reason you didn't use `simplified_tuning apply` in the filter settings? This command sets the proper values for the active sliders only

No reason, I'll add that line.

2024-11-06 15:42 UTC, haslinghuis approved these changes

2024-11-07 05:19 UTC, merged