Create HDZero_race2 vtx table
betaflight/firmware-presets pull request #83
Opened 2021-11-14 06:06 UTC by sugaarK

vtx table for new 20x20 race VTX from HDzero

manual found here

[HDzero race2 manual]( https://28003cc0-88ab-4618-8fa6-9747a051df97.filesusr.com/ugd/ea052e_18c5903fbb13440b8d3831a965ea8a37.pdf?fbclid=IwAR2MdGKn8dIcT90CAUp74sYg4ycZYn87aOQpy_Fe5KYzVkfovMFpVew2sok)

2021-11-14 08:32 UTC, limonspb requested changes

2021-11-14 08:32 UTC, limonspb commented on presets/4.3/vtx/HDZero_race2.txt
> +#$ TITLE: TBS Unify Pro32 Nano - SA 2.1
Title :)

2021-11-14 09:14 UTC, sugaarK commented on presets/4.3/vtx/HDZero_race2.txt
> +#$ TITLE: TBS Unify Pro32 Nano - SA 2.1
opps yeah

2021-11-15 05:57 UTC, limonspb reviewed
According to HDZero manual, it is a SmartAudio 2.1. For SA 2.1 power values should be in db.
However, the VTX table shared in the manual it shows `powervalues 1 2 3`

I guess it's a question to the HDZero developers, is that a typo in the user manual or something else?
![image](https://user-images.githubusercontent.com/2925027/141729881-10b845f5-3d5c-47b8-9a82-a1e9005627ca.png)

2021-11-17 02:47 UTC, limonspb commented
seems like HDzero are about to fix something:
![image](https://user-images.githubusercontent.com/2925027/142117235-a103c3df-83c4-4a05-8caa-a45f0edfa2ad.png)

2021-11-17 06:07 UTC, closed without merging