UAV Tech rates
betaflight/firmware-presets pull request #91
Opened 2021-11-26 21:37 UTC by limonspb

![uavTech](https://user-images.githubusercontent.com/2925027/143656557-31774099-4fab-4093-9176-3962724ced54.png)

2021-11-26 23:56 UTC, ctzsnooze commented
These are plainly not 'race' rates.  They are freestyle and probably also suitable for cinematic or HD filming also.

It would be good to include the keywords `freestyle`, `HD`, `cinematic` I think.

I don't think `youtube` is appropriate as a keyword :-)

2021-11-27 01:07 UTC, limonspb commented
> These are plainly not 'race' rates. They are freestyle and probably also suitable for cinematic or HD filming also.
> 
> The description should probably say "Freestyle rates by...."
> 
> It would be good to include the keywords `freestyle`, `HD`, and `cinematic`.
> 
> I don't think `youtube` is appropriate as a keyword :-)

Done! I also think it's appropriate to change them to Official as Mark is a BF contributor and an active "skunk" participant.

2021-11-27 01:34 UTC, ctzsnooze commented
We would not include 'advertising' like this, especially in `OFFICIAL` presets:

```
#$ DESCRIPTION: UAV Tech - a YouTube channel about FPV with some deep dives into tuning and blackbox analyzing. Mark is also a Betaflight contributor that prioritizes data over feelings.
```

The description in an `OFFICIAL` preset should be about the flight characteristics of the rates, it's advantages or whatever. It should not be advertising for the youtube channel of the contributor.  

Even in a `COMMUNITY` preset, I think we should be cautious about accepting 'advertising' of that kind.  

Our goal with Betaflight hosted Presets is not to provide an advertising for products or services.  

If we allow this, we probably will get flooded with useless presets intended primarily for advertising, which may well not be a useful addition to the range of presets provided.

2021-11-27 04:23 UTC, ctzsnooze approved these changes

2021-11-27 05:53 UTC, sugaarK requested changes

2021-11-27 05:53 UTC, sugaarK commented on presets/4.3/rates/UAV_tech.txt
> +#$ STATUS: OFFICIAL
This should be community

2021-11-27 05:53 UTC, sugaarK commented on presets/4.3/rates/UAV_tech.txt
> +#$ KEYWORDS: UAV Tech, youtube, freestyle, HD, cinematic
I agree with CT here remove the YouTube.

2021-11-27 05:53 UTC, sugaarK commented on presets/4.3/rates/UAV_tech.txt
> +#$ DESCRIPTION: Mark is a Betaflight contributor and tuner who prioritizes data over feelings. His YouTube channel includes some deep dives into tuning and blackbox analyzing.
I’m ok with this Mark has been part of the works for a long time and is considered the gateway between BF and YouTube.

2021-11-27 06:43 UTC, merged